/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package net.mconcoba.views;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author mconcoba
 */
public class LoginView extends javax.swing.JFrame {

    private ImageIcon imagen;
    private Icon icono;
    
    public LoginView() {
        initComponents();
        
        this.mostartImagen(back, "src/net/mconcoba/resource/fondo.png");
        this.showControllers();
    }
    
    private void mostartImagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_DEFAULT));
        lbl.setIcon(icono);
        
        this.repaint();
        
    }
    
    public void showControllers(){
        tbl_error.hide();
    
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fondo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnl_session = new javax.swing.JPanel();
        txt_user = new rojeru_san.RSMTextFull();
        txt_password = new rojeru_san.RSMPassView();
        teach = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tbl_error = new javax.swing.JLabel();
        btn_login = new rojeru_san.RSButtonRiple();
        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JLabel();

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fondo.setFocusCycleRoot(true);
        fondo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        pnl_session.setBackground(new java.awt.Color(255, 255, 255));
        pnl_session.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnl_session.setToolTipText("");
        pnl_session.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnl_session.setFocusCycleRoot(true);
        pnl_session.setInheritsPopupMenu(true);
        pnl_session.setName("pnl_session"); // NOI18N
        pnl_session.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_user.setPlaceholder("Usuario...");
        pnl_session.add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 300, -1));

        txt_password.setPlaceholder("Contraseña");
        pnl_session.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 300, -1));

        teach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/mconcoba/resource/teach.png"))); // NOI18N
        teach.setAutoscrolls(true);
        teach.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        teach.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        teach.setName(""); // NOI18N
        pnl_session.add(teach, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 120, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/mconcoba/resource/pass.png"))); // NOI18N
        pnl_session.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/mconcoba/resource/user.png"))); // NOI18N
        pnl_session.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        tbl_error.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        tbl_error.setForeground(new java.awt.Color(204, 0, 0));
        tbl_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tbl_error.setText("Usuario o contraseña incorrecta");
        pnl_session.add(tbl_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, 40));

        btn_login.setText("Iniciar Sesion");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        pnl_session.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 109;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(103, 33, 0, 50);
        jPanel2.add(pnl_session, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(380, 373));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 550, 550));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 170;
        gridBagConstraints.ipady = 177;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(59, 49, 104, 0);
        jPanel2.add(jPanel1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1092, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_loginActionPerformed

  
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private rojeru_san.RSButtonRiple btn_login;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnl_session;
    private javax.swing.JLabel tbl_error;
    private javax.swing.JLabel teach;
    private rojeru_san.RSMPassView txt_password;
    private rojeru_san.RSMTextFull txt_user;
    // End of variables declaration//GEN-END:variables
}
